version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/application
    working_dir: /application
    ports:
      - "9000:9000"
    command: tail -F anything

  mysql:
    image: library/mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
