services:
  php:
    image: ghcr.io/ame180/sunny-camping-app:latest
    env_file:
      - .env
    volumes:
      - app_storage:/application/storage
    working_dir: /application
    entrypoint: "/bin/bash /application/infrastructure/entrypoint-prod.sh"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: ghcr.io/ame180/sunny-camping-nginx:latest
    working_dir: /application
    depends_on:
      - php
    volumes:
      - app_storage:/application/storage:ro
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST}
    restart: unless-stopped

  mysql:
    image: library/mariadb:10.5
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  app_storage:
  dbdata:
